name: build python
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - python/**
jobs:
  push:
    name: "ampimages:python_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 2.7
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./python
          file: ./python/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/goover/ampimages:python_${{ matrix.tag }}
